### ISSUE TITLE
handling more than a single dust file

### ISSUE THREAD

**Issue by tsullivan** [ehynds/grunt-dust-html#15]
Hi, I am trying to figure out the way of using grunt-dust-html to handle multiple dust files. 

Say I have a directory of Dust files:

```
src/templates/examples
├── page-not-found.dust
└── index.dust
```

And I want to render HTML into an `examples` folder in the project root.

```
examples
├── page-not-found.html
└── index.html
```

I'm stuck on how to configure the grunt task to do this. It doesn't seem like the 'src' option can be a glob or that the 'dest' option can be a directory.

**Comment by mikehedman** [comment]
Hi,
One problem with the given solution is that the output files still have the .dust extension.  This can be remedied with the grunt rename feature:

```
dusthtml: {
      all: {
        files: [{
          expand: true,
          cwd: 'src/templates/examples',
          src: '*.dust',
          dest: 'examples/',        
          rename: function(dest, src) {
              return dest + src.replace('.dust','.html');
          }
        }]
    }
}
```

**Comment by maniskasyap** [comment]
I am facing an issue while working on multiple dust files in different folders.
Here is my grunt task config:

``` javascript
module.exports = {     
    dev: {
      files: [
        {
            expand: true, 
            cwd: '<%= globalConfig.src %>',
            src: '*.dust',
            dest: '<%= globalConfig.dist %>/',
            rename: function(dest, src) {
              return dest + src.replace('.dust','.html');
            }
        },
        {
            expand: true, 
            cwd: '<%= globalConfig.src %>/views/common',
            src: '*.dust',
            dest: '<%= globalConfig.dist %>/views/common/',
            rename: function(dest, src) {
              return dest + src.replace('.dust','.html');
            }
        }
      ],
      options: {
        partialsDir: '<%= globalConfig.src %>/partials',
        whitespace: true,
        context: {
            pageTitle:'MyApp'
        }
      }
    }
};
```

The problem comes when files array has above two entries. It sometimes doesn't create _index.html_ from _index.dust_ which is present at **globalConfig.src**. 
Please let me know if more details are needed or i am missing something here.
