### ISSUE TITLE
fix the wrong promise call

### ISSUE THREAD

**Issue by didoo** [ehynds/grunt-dust-html#20]
There is already a pull request opened for this issue:
https://github.com/ehynds/grunt-dust-html/pull/19

Any chance to see it merged? If fixes a problem with the async generation of the templates, that return before actually completing.

**Comment by signate** [comment]
Looks like developer doesn't support this anymore. I have a fork of this repository with this issue fixed and also without some unnecessary dependencies: https://github.com/signate/grunt-dust-html

You can try it by changing grunt-dust-html in packages.json to:
`"grunt-dust-html": "https://github.com/signate/grunt-dust-html/tarball/18bae12126ab89672a7cedd3456bede88dc8e99c"`

**Comment by signate** [comment]
Fixed in a fork: https://github.com/signate/grunt-dust-html
